<?php
/**
 * Default Language file for CodeMirror
 *
 * @package codemirror
 * @subpackage lexicon
 */
$_lang['setting_directresize.path'] = 'Thumbnail path';
$_lang['setting_directresize.path_desc'] = 'Folder for storing the images generated by the plugin, this folder will be created if it does not exist.';

$_lang['setting_directresize.prefix'] = 'Image prefix';
$_lang['setting_directresize.prefix_desc'] = 'Prefix for the images, this is used to ensure that the image filename is unique.';

$_lang['setting_directresize.size_rule'] = 'Rules for sizing';
$_lang['setting_directresize.size_rule_desc'] = '0: proportional to the width and height;<br /> 1: based on the width;<br /> 2: based on height;<br /> 3: The maximum width and height;<br /> 4: The image fills the container is full width and height.';

$_lang['setting_directresize.q_jpg'] = 'jpg quality';
$_lang['setting_directresize.q_jpg_desc'] = 'from 0 to 100';

$_lang['setting_directresize.q_png'] = 'png compression';
$_lang['setting_directresize.q_png_desc'] = 'from 0 to 9';

$_lang['setting_directresize.path_base'] = 'Path for the images';
$_lang['setting_directresize.path_base_desc'] = 'Define the path to the folder containing the images to be used by the plugin.';

$_lang['setting_directresize.lightbox'] = 'Activating lightbox';
$_lang['setting_directresize.lightbox_desc'] = '0: not active;<br /> 1: activate the lightbox only contains the class; <br /> 2: activation for all images';

$_lang['setting_directresize.lightbox_w'] = 'Max. width';
$_lang['setting_directresize.lightbox_w_desc'] = 'Define maximum width for expanded images.';

$_lang['setting_directresize.lightbox_h'] = 'Max. height';
$_lang['setting_directresize.lightbox_h_desc'] = 'Define maximum height for expanded images.';
